[build]
  command = "npm install && npm run build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  CLAUDE_API_KEY = ""
  NEXT_PUBLIC_CLAUDE_API_KEY = ""
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@anthropic-ai/sdk"]

[functions.analyze-conversation]
  included_files = ["public/data/**"]
  timeout = 60

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = ".next"
  functions = "netlify/functions"
  autoLaunch = true

[dev.environment]
  NODE_ENV = "development"
  NETLIFY_DEV = "true"
  DEBUG = "*"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 