[build]
  command = "npm install --production=false && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NODE_ENV = "production"
  DEBUG = "*"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@anthropic-ai/sdk", "uuid"]
  pattern = "analyze-conversation"
  included_files = ["public/data/*"]
  timeout = 60

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/analyze-conversation"
  to = "/.netlify/functions/analyze-conversation"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = ".next"
  functions = "netlify/functions"
  autoLaunch = true

[dev.environment]
  NODE_ENV = "development"
  NETLIFY_DEV = "true"
  DEBUG = "*"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 