[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  included_files = ["public/data/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = ".next"
  functions = "netlify/functions"
  autoLaunch = true

[dev.environment]
  NODE_ENV = "development"
  NETLIFY_DEV = "true"
  DEBUG = "*"

[build.environment]
  CLAUDE_API_KEY = "sk-ant-api03-..."
  NEXT_PUBLIC_CLAUDE_API_KEY = "sk-ant-api03-..."
  DEBUG = "*"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions.analyze-conversation]
  included_files = ["public/data/**"]
  timeout = 60 