[build]
  command = "npm install --production=false && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NETLIFY = "true"
  
  # Configure Netlify Blobs properly
  # These will be set by netlify env:set
  # NETLIFY_SITE_ID = "your-site-id"
  # NETLIFY_ACCESS_TOKEN = "your-access-token"
  
  # Ensure we're using KV storage
  JOB_STORAGE_TYPE = "kv"
  JOB_MAX_AGE = "86400000"
  
  # Enable Blobs
  NETLIFY_BLOBS_ENABLED = "true"
  DEBUG = "*"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@anthropic-ai/sdk", "uuid", "@netlify/blobs"]
  included_files = ["netlify/functions/**/*"]

# Enable Netlify Blobs (KV Store)
[[edge_functions]]
  function = "analyze-conversation"
  path = "/api/analyze-conversation"

[[edge_functions]]
  function = "check-job-status"
  path = "/api/check-job-status"

[[edge_functions]]
  function = "analyze-conversation-background"
  path = "/api/analyze-conversation-background"

[[edge_functions]]
  function = "force-complete-job"
  path = "/api/force-complete-job"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/analyze-conversation"
  to = "/.netlify/functions/analyze-conversation"
  status = 200
  force = true

[[redirects]]
  from = "/api/check-job-status"
  to = "/.netlify/functions/check-job-status"
  status = 200
  force = true

[[redirects]]
  from = "/api/force-complete-job"
  to = "/.netlify/functions/force-complete-job"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = ".next"
  functions = "netlify/functions"
  autoLaunch = true

[dev.environment]
  NODE_ENV = "development"
  NETLIFY_DEV = "true"
  DEBUG = "*"
  # For local development, use memory storage instead of KV store
  JOB_STORAGE_TYPE = "memory"
  JOB_MAX_AGE = "86400000"
  # Local development Blobs configuration
  NETLIFY_BLOBS_ENABLED = "true"
  # These will be set by netlify dev
  # NETLIFY_SITE_ID = "dev-site-id"
  # NETLIFY_ACCESS_TOKEN = "dev-access-token"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Increase timeout for functions that may take longer
[functions.analyze-conversation]
  timeout = 300

[functions.analyze-conversation-background]
  timeout = 900

[functions.force-complete-job]
  timeout = 30 