services:
  - type: web
    name: winery-sales-evaluator
    env: node
    plan: standard
    buildCommand: npm install && npm run build && chmod +x render-setup.sh
    startCommand: ./render-setup.sh && node server.js
    nodeVersion: 18.x # Next.js recommended version
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLAUDE_API_KEY
        sync: false # Indicates this should be set manually in Render dashboard
      - key: GEMINI_API_KEY
        sync: false
      - key: RENDER
        value: "true"
      - key: RENDER_STORAGE_DIR
        value: /opt/render/project/src/.render/storage
      - key: JOB_STORAGE_TYPE
        value: file
      - key: JOB_MAX_AGE
        value: "86400000"
      - key: NEXT_PUBLIC_USE_DIRECT_EVALUATION
        value: "false"
      - key: PORT
        value: "10000"
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      cpu: 1000m # 1 CPU
      memory: 2Gi # 2GB RAM
    healthCheckPath: /api/health
    autoDeploy: true
    domains:
      - fromEnv: RENDER_EXTERNAL_URL
    # Add build-time environment variables if needed
    buildEnv:
      - key: NEXT_TELEMETRY_DISABLED
        value: "1" 