services:
  - type: web
    name: wine-sales-evaluator
    env: node
    buildCommand: npm ci --include=dev && npm run build && chmod +x render-setup.sh
    startCommand: ./render-setup.sh && node server.js
    healthCheckPath: /api/health
    # Define a persistent disk for storage
    disk:
      name: wine-evaluator-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: CLAUDE_API_KEY
        sync: false # This will be set via Render dashboard
      - key: GEMINI_API_KEY
        sync: false # This will be set via Render dashboard
      - key: RENDER_STORAGE_DIR
        value: /var/data/storage
      - key: JOB_STORAGE_TYPE
        value: file
      - key: JOB_MAX_AGE
        value: "86400000"
      - key: NEXT_PUBLIC_USE_DIRECT_EVALUATION
        value: "false"
      - key: PORT
        value: "10000"
    # Add build-time environment variables if needed
    buildEnv:
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    # Auto-deploy settings
    autoDeploy: true 